dist: trusty
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10
before_script:
  - cp config.template.js config.js
script:
  - npm run check-source-formatting
  - npm run lint
  - npm run check-types
  - npm run test
  - npm run build
