name: Check pre-compiled i18n

on:
  push:
    branches-ignore:
      - 'integration/**'
  pull_request:

jobs:
  check-compiled-i18n:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: cp config.template.js config.js
    - run: npm install
    - run: npm run check-compiled-i18n
      env:
        FLOOD_SECRET: ${{ secrets.FLOOD_SECRET }}
