name: Check

on:
  push:
    branches-ignore:
      - 'integration/**'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [14]
        check: [check-compiled-i18n, check-source-formatting, check-types, lint]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: cp config.cli.js config.js
    - run: npm install
    - run: npm run ${{ matrix.check }}
