name: Lint

on:
  push:
    branches-ignore:
      - 'integration/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: cp config.cli.js config.js
    - run: npm install
    - run: npm run lint
