name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [15]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - run: sudo npm i -g pkg
      - run: npm ci

      - run: npm run build-pkg
      - run: git fetch origin refs/tags/v4.1.1
      - run: git for-each-ref refs/tags/v4.1.1 --format="%(contents)" > body

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release v4.1.1
          tag_name: refs/tags/v4.1.1
          body_path: body
          files: |
            dist-pkg/flood-linux
            dist-pkg/flood-macos
            dist-pkg/flood-win.exe
